services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel
    restart: unless-stopped
    tty: true
    expose:
      - "9000"
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www
      - ./php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - thtapi_api_laravel
  postgres:
    image: postgres:13
    container_name: postgres-container
    environment:
      POSTGRES_DB: laravel_db
      POSTGRES_USER: laravel_user
      POSTGRES_PASSWORD: laravel_password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - thtapi_api_laravel
  # Nginx Service
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    tty: true
    expose:
      - "85"
    ports:
      - "8585:85"
    volumes:
      - ./app:/var/www
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel
    networks:
      - thtapi_api_laravel

networks:
  thtapi_api_laravel:
    external: true

volumes:
  postgres-data:
    driver: local
