<?php

namespace App\Providers;

use App\Service\AkunService;
use App\Service\Impl\AkunServiceImpl;
use Illuminate\Contracts\Support\DeferrableProvider;
use Illuminate\Support\ServiceProvider;

class AkunServiceProvider extends ServiceProvider implements DeferrableProvider
{
    /**
     * Register services.
     */
    public function register(): void
    {
        $this->app->singleton(AkunService::class, AkunServiceImpl::class);

    }

    /**
     * Bootstrap services.
     */
    public function boot(): void
    {
        //
    }

    public function provides()
    {
        return [AkunService::class]; // TODO: Change the autogenerated stub
    }
}
