<?php

namespace App\Providers;

use App\Service\Impl\KategoriServiceImpl;
use App\Service\KategoriService;
use Illuminate\Contracts\Support\DeferrableProvider;
use Illuminate\Support\ServiceProvider;

class KategoriServiceProvider extends ServiceProvider implements DeferrableProvider
{
    /**
     * Register services.
     */
    public function register(): void
    {
        $this->app->singleton(KategoriService::class, KategoriServiceImpl::class);

    }

    /**
     * Bootstrap services.
     */
    public function boot(): void
    {
        //
    }

    public function provides()
    {
        return [KategoriService::class]; // TODO: Change the autogenerated stub
    }
}
