<?php

namespace App\Providers;

use App\Service\Impl\ProdukServiceImpl;
use App\Service\ProdukService;
use Illuminate\Contracts\Support\DeferrableProvider;
use Illuminate\Support\ServiceProvider;

class ProdukServiceProvider extends ServiceProvider implements DeferrableProvider
{
    /**
     * Register services.
     */
    public function register(): void
    {
        $this->app->singleton(ProdukService::class, ProdukServiceImpl::class);
    }

    /**
     * Bootstrap services.
     */
    public function boot(): void
    {
        //
    }

    public function provides()
    {
        return [ProdukService::class]; // TODO: Change the autogenerated stub
    }
}
